### ISSUE TITLE
SumoEasyMiner works on Ubuntu 17.10!

### ISSUE THREAD

**Issue by ghost** [sumoprojects/SumoEasyMiner#12]
Sorry for opening an issue for this. I will also create a pull request to add these instructions to the README.

I had pretty much the same issues compiling and executing SumoEasyMiner as most people here.

My system (you can check the installed and to be installed version by executing `sudo apt-cache policy [package-name]`).
- ubuntu 17.10
- python 2.7.14
- cmake 3.9.1-1
- gcc 4:7.2.0-1
- python-dev 2.7.14-2
- python-pip 9.0.1-2
- python-pyside 1.2.2+source1-1build1
- psutil 5.4.3

Here are the steps to get it to work:

- Clone or [download SumoEasyMiner repo](https://github.com/sumoprojects/SumoEasyMiner/archive/master.zip).
- Clone or [download cryptonight-hash-lib](https://github.com/sumoprojects/cryptonight-hash-lib/archive/master.zip).
- `sudo apt-get install cmake gcc python-dev python-pip python-pyside`
-  `pip install psutil`
- `cd /path/to/cryptonight-hash-lib`
- `cmake .`
The last lines of the output should look something like this:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/cryptonight-hash-lib
```
- `make`
The last lines of the output should look something like this:
```
[100%] Linking C shared library cryptonite_hash.so
[100%] Built target cryptonite_hash
```
- Copy just created `cryptonite_hash.so` from `cryptonight-hash-lib` folder to `/path/to/SumoEasyMiner/libs` folder
```
- Run the miner with `python sumominer.py`
- Start mining

**Comment by themyth92** [comment]
Hi there, you know how to configure the wallet address and pool address using command line ?
I currently stuck at configuration and the error I receive when running `python sumominer.py` is `sumominer.py: cannot connect to X server`. Thank you !

**Comment by ghost** [comment]
@themyth92 You can change the wallet and pool directly in sumominer but it sounds like sumominer isn't executing. Have you tried to search for the error on stackoverflow, ...?

**Comment by themyth92** [comment]
No, I have not found any solutions for command line, so I switch to using [xmr-stak](https://github.com/fireice-uk/xmr-stak) for my ubuntu instead.

**Comment by ghost** [comment]
Good idea. Closing this issue
